# Meta data
name:         Photon
authors:      Nicholas Berlette and Connor Sears
description:  Build desktop apps with simple HTML and CSS components.

# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Server
source:       docs
port:         4000
url:          https://photon.berlette.com
